language: python

python:
#  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
#  - 3.7-dev

cache: pip
sudo: false

addons:
  apt:
    packages:
      - build-essential
      - inotify-tools
      - python3-dev
      - libssl-dev
      - python3-dbus

install:
  - pip install -U pip
  - pip3 install -U setuptools
  - pip3 install coverage coveralls pytest
  - python3 setup.py install

before_script:
  - python3 --version

script:
  - python3 -m pytest
  - coverage3 run --branch --source=onedrived setup.py test

after_success:
  - coverage3 report -m
  - coveralls

notifications:
  email: false
